[package]
name = "scratch-test"
version = "0.1.0"
edition = "2024"
default-run = "scratch-test"

[workspace.dependencies]
thiserror = "2.0.16"

[dependencies]
derive_more = { version = "2.0.1", features = ["display", "from"] }
serde_json = "1.0.145"
thiserror = "2.0.16"
zip = { version = "5.1.1", default-features = false, features = ["deflate64", "deflate"] }
log = "0.4.28"

model = { path = "crates/model" }
interpreter = { path = "crates/interpreter" }
testdata = { path = "crates/testdata" }
testreports = { path = "crates/testreports" }

clap = { version = "4.5.48", features = ["derive"] }
dotenvy = "0.15.7"
env_logger = "0.11.8"
alphanumeric-sort = "1.5.3"
colored = "3.0.0"
itertools = "0.14.0"

[workspace]
members = ["crates/interpreter","crates/model", "crates/testdata", "crates/testreports"]
